### ISSUE TITLE
what's next?

### ISSUE THREAD

**Issue by diego-vieira** [ya-kostik/sails-hook-sequelize-pubsub#1]
@ya-kostik very interested on this since I'm moving to sequelize.
Would be glad to know how can I help.

Thanks

**Comment by ya-kostik** [comment]
Sorry for the long answer. Could not deal with this issue.
At the moment I'm left from Sails.
Everything you need to implement pusub on sequelize is to replace the fields of native Waterline models to the fields of sequelize models. Unfortunately now I can't do this. Maybe later. I'll let you know if something happens. If you find or create the solution, please leave feedback in this matter.

Sincerely yours.

**Comment by diego-vieira** [comment]
@ya-kostik me too, not using sails anymore. Thank you anyway.
